CREATE TABLE IS601_Anime (
    id INT AUTO_INCREMENT PRIMARY KEY,
    api_id VARCHAR(20) DEFAULT NULL,
    title VARCHAR(100) UNIQUE NOT NULL,
    alternativeTitles VARCHAR(100) NOT NULL,
    ranking INTEGER NOT NULL,
    genres VARCHAR(100) NOT NULL,
    episodes INTEGER,
    status VARCHAR(30),
    type VARCHAR(20),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
